### ISSUE TITLE
Error in French Translation

### ISSUE THREAD

**Issue by robertvunabandi** [diniska/chemistry#7]
Hey, I love your project. I only looked at the Periodic Table document so far, and I found a mistake.

The translation for boron and carbon to french is wrong:
"Boron" is "Bore" in French
"Carbon" is "Carbone" in French

Hopefully, these gets fixed. Also, I agree on the license. I'd love to be able to use this as well :)

Here's an image of what the error looks like.
<img width="317" alt="screen shot 2017-01-09 at 12 43 50 pm" src="https://cloud.githubusercontent.com/assets/23228006/21776700/b41ba288-d669-11e6-9bef-c6b5fd5908cd.png">

Thanks

**Comment by AltGen** [comment]
thanks for your advice, I included your changes in my pull request. Now are officially updated
